//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMaid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMaid.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shouldn&apos;t run this app with elevated privileges. Don&apos;t risk your PC! (:.
        /// </summary>
        internal static string AdminErrorMessage {
            get {
                return ResourceManager.GetString("AdminErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnBidFarewell_Text {
            get {
                return ResourceManager.GetString("btnBidFarewell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string btnSendLetter_Text {
            get {
                return ResourceManager.GetString("btnSendLetter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat thread has started..
        /// </summary>
        internal static string ChatStart {
            get {
                return ResourceManager.GetString("ChatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat thread has stopped..
        /// </summary>
        internal static string ChatStop {
            get {
                return ResourceManager.GetString("ChatStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatWindowTitle {
            get {
                return ResourceManager.GetString("ChatWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command thread has started..
        /// </summary>
        internal static string CommandStart {
            get {
                return ResourceManager.GetString("CommandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command thread has stopped..
        /// </summary>
        internal static string CommandStop {
            get {
                return ResourceManager.GetString("CommandStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection thread has started..
        /// </summary>
        internal static string ConnectionStart {
            get {
                return ResourceManager.GetString("ConnectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection thread has stopped..
        /// </summary>
        internal static string ConnectionStop {
            get {
                return ResourceManager.GetString("ConnectionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMD injection attempt detected!.
        /// </summary>
        internal static string InjectionErrorMessage {
            get {
                return ResourceManager.GetString("InjectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, setup a password: .
        /// </summary>
        internal static string PasswordEnterTip {
            get {
                return ResourceManager.GetString("PasswordEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too weak..
        /// </summary>
        internal static string PasswordWeakHint {
            get {
                return ResourceManager.GetString("PasswordWeakHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can you be when the world can only see a monster?.
        /// </summary>
        internal static string PastSins {
            get {
                return ResourceManager.GetString("PastSins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no setting named: .
        /// </summary>
        internal static string SettingErrorMessage {
            get {
                return ResourceManager.GetString("SettingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string SupportName {
            get {
                return ResourceManager.GetString("SupportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time thread has started..
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem connecting to server. Check your internet connection..
        /// </summary>
        internal static string WebErrorMessage {
            get {
                return ResourceManager.GetString("WebErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command typo: .
        /// </summary>
        internal static string WrongCommandErrMsg {
            get {
                return ResourceManager.GetString("WrongCommandErrMsg", resourceCulture);
            }
        }
    }
}
